apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
  namespace: kube-system
data:
  traefik.toml: |
    InsecureSkipVerify = true
    defaultEntryPoints = ["http", "https"]

    [traefikLog]
      format = "json"

    [healthcheck]

    [entryPoints]
      [entryPoints.http]
        address = ":80"
        compress = true
        [entryPoints.http.redirect]
          entryPoint = "https"
      [entryPoints.https]
        address = ":443"
        compress = true
        [entryPoints.https.tls]

    [retry]
      attempts = 3

    [web]
      address = ":8080"

    [kubernetes]

    [consul]
      endpoint = "consul:8500"
      watch = true
      prefix = "traefik"

    [forwardingTimeouts]
      dialTimeout = "10s"

    [acme]
      email = "[EMAIL]"
      storage = "traefik/acme/account"
      entryPoint = "https"
      onDemand = true
      onHostRule = true
      acmeLogging = true
      [acme.dnsChallenge]
        provider = "cloudflare"
        delayBeforeCheck = 0
      [[acme.domains]]
        main = "*.[DOMAIN]"
