apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      labels:
        name: weave-scope
      name: weave-scope
      annotations:
        cloud.weave.works/launcher-info: |-
          {
            "server-version": "master-6a6f8a1",
            "original-request": {
              "url": "/k8s/v1.5/scope.yaml?/launch/k8s/weavescope.yaml",
              "date": "Tue May 09 2017 11:15:57 GMT+0000 (UTC)"
            },
            "email-address": "support@weave.works"
          }
  - apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      labels:
        name: weave-scope-app
        app: weave-scope
        weave-cloud-component: scope
        weave-scope-component: app
      name: weave-scope-app
      annotations:
        cloud.weave.works/launcher-info: |-
          {
            "server-version": "master-6a6f8a1",
            "original-request": {
              "url": "/k8s/v1.5/scope.yaml?/launch/k8s/weavescope.yaml",
              "date": "Tue May 09 2017 11:15:57 GMT+0000 (UTC)"
            },
            "email-address": "support@weave.works"
          }
    spec:
      replicas: 1
      template:
        metadata:
          labels:
            name: weave-scope-app
            app: weave-scope
            weave-cloud-component: scope
            weave-scope-component: app
        spec:
          containers:
            - name: app
              image: 'weaveworks/scope:1.9.1'
              imagePullPolicy: IfNotPresent
              args:
                - '--no-probe'
              ports:
                - containerPort: 4040
                  protocol: TCP
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        name: weave-scope-app
        app: weave-scope
        weave-cloud-component: scope
        weave-scope-component: app
      name: weave-scope-app
      annotations:
        cloud.weave.works/launcher-info: |-
          {
            "server-version": "master-6a6f8a1",
            "original-request": {
              "url": "/k8s/v1.5/scope.yaml?/launch/k8s/weavescope.yaml",
              "date": "Tue May 09 2017 11:15:57 GMT+0000 (UTC)"
            },
            "email-address": "support@weave.works"
          }
    spec:
      ports:
        - name: app
          port: 80
          targetPort: 4040
          protocol: TCP
      selector:
        name: weave-scope-app
        app: weave-scope
        weave-cloud-component: scope
        weave-scope-component: app
  - apiVersion: extensions/v1beta1
    kind: DaemonSet
    metadata:
      labels:
        name: weave-scope-agent
        app: weave-scope
        weave-cloud-component: scope
        weave-scope-component: agent
      name: weave-scope-agent
      annotations:
        cloud.weave.works/launcher-info: |-
          {
            "server-version": "master-6a6f8a1",
            "original-request": {
              "url": "/k8s/v1.5/scope.yaml?/launch/k8s/weavescope.yaml",
              "date": "Tue May 09 2017 11:15:57 GMT+0000 (UTC)"
            },
            "email-address": "support@weave.works"
          }
    spec:
      template:
        metadata:
          labels:
            name: weave-scope-agent
            app: weave-scope
            weave-cloud-component: scope
            weave-scope-component: agent
          annotations:
            scheduler.alpha.kubernetes.io/tolerations: >-
              [{"key":"dedicated","operator":"Equal","value":"master","effect":"NoSchedule"}]
        spec:
          containers:
            - name: agent
              image: 'weaveworks/scope:1.9.1'
              imagePullPolicy: IfNotPresent
              args:
                - '--no-app'
                - '--probe.docker.bridge=docker0'
                - '--probe.docker=true'
                - '--probe.kubernetes=true'
                - >-
                  $(WEAVE_SCOPE_APP_SERVICE_HOST):$(WEAVE_SCOPE_APP_SERVICE_PORT)
              securityContext:
                privileged: true
              volumeMounts:
                - name: docker-socket
                  mountPath: /var/run/docker.sock
                - name: scope-plugins
                  mountPath: /var/run/scope/plugins
          volumes:
            - name: docker-socket
              hostPath:
                path: /var/run/docker.sock
            - name: scope-plugins
              hostPath:
                path: /var/run/scope/plugins
          hostPID: true
          hostNetwork: true
          serviceAccountName: weave-scope
  - apiVersion: extensions/v1beta1
    kind: Ingress
    metadata:
      name: weave-scope-ui
      annotations:
        kubernetes.io/ingress.class: traefik
    spec:
      rules:
      - host: weavescope.REPLACE-WITH-DOMAIN
        http:
          paths:
          - backend:
              serviceName: weave-scope-app
              servicePort: 80
