apiVersion: batch/v1
kind: Job
metadata:
  name: certbot-boostrap
  namespace: kube-system
spec:
  template:
    metadata:
      name: certbot-boostrap
    spec:
      containers:
        - image: gcr.io/GCP-PROJECT-ID/certbot-bootstrap
          name: certbot-bootstrap
          env:
            - name: DOMAIN
              value: REPLACE-WITH-DOMAIN
            - name: EMAIL
              value: REPLACE-WITH-EMAIL
            - name: KONG_ADDR
              value: kong-ingress-controller:8001
      restartPolicy: Never